name: 01-Building Blocks

on: workflow_dispatch

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Radhe
              run: echo "Radhe, Radhe!" 
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed Step # This step will fail
              run: 
                exit 1
            - name: Say Goodbye
              run: echo "Goodbye, Nainy!"