name: Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

    # 0. Checkout code from repo
    # 1. Install deps for our react app
    # 2. Execute automated tests

    